version: '3'
volumes: 
    data:
services:
    web:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - '.:/RailsMySQLSample'
        tty: true
        stdin_open: true
        environment:
            - 'DATABASE_PASSWORD=password' 
        depends_on: 
            - db
        links:
            - db
    db:
        image: mysql:5.7
        ports:
            - '3001:3001'
        volumes:
            - 'data:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password